serviceAccount: projects/regal-stone-481911-e6/serviceAccounts/cloud-build-sa@regal-stone-481911-e6.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest
    - .

images:
- us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest