serviceAccount: projects/$PROJECT_ID/serviceAccounts/cloud-build-sa@$PROJECT_ID.iam.gserviceaccount.com

timeout: "1200s"

substitutions:
  _REGION: us-central1
  _REPO: docker-repo
  _IMAGE: app
  _TERRAFORM_DIR: terraform

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # ------------------------
  # 1️⃣ Build Docker Image
  # ------------------------
  - id: "Build Docker Image"
    name: gcr.io/cloud-builders/docker
    dir: app
    args:
      - build
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest"
      - .

  # ------------------------
  # 3️⃣ Terraform Init
  # ------------------------
  - id: "Terraform Init"
    name: hashicorp/terraform:1.6
    dir: "${_TERRAFORM_DIR}"
    args:
      - init
      - "-input=false"

  # ------------------------
  # 4️⃣ Terraform Apply
  # ------------------------
  - id: "Terraform Apply"
    name: hashicorp/terraform:1.6
    dir: "${_TERRAFORM_DIR}"
    args:
      - apply
      - "-auto-approve"
      - "-input=false"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest"