steps:
# 1. Terraform Init & Apply
- name: hashicorp/terraform
  args: ["init"]
  dir: "terraform"

- name: hashicorp/terraform
  args: ["apply", "-auto-approve"]
  dir: "terraform"

# 2. Build Docker image in Cloud Build
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest',
      'app'
    ]

# 3. Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest'
    ]

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest