steps:
  # Step 1: Build Docker image for your app
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest'
      - '-f'
      - 'app/Dockerfile'   # Dockerfile is inside the app folder
      - 'app'              # Build context points to the app folder

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest'

  # Step 3: Terraform init
  - name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init \
          -backend-config="bucket=regal-stone-481911-terraform-state" \
          -backend-config="prefix=terraform/state" \
          -reconfigure

  # Step 4: Terraform plan
  - name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - terraform plan

  # Step 5: Terraform apply
  - name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - terraform apply -auto-approve

options:
  logging: CLOUD_LOGGING_ONLY