steps:
  # Step 1: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest
      - .

  # Step 2: Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest

  # Step 3: Terraform Init
  - name: hashicorp/terraform
    dir: terraform
    args:
      - init

  # Step 4: Terraform Apply (THIS WAS MISSING)
  - name: hashicorp/terraform
    dir: terraform
    args:
      - apply
      - -auto-approve