# cloudbuild.yaml

steps:
  # 1️⃣ Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest",
        "app"
      ]

  # 2️⃣ Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest"
      ]

  # 3️⃣ Terraform Init (with backend config for GCS)
  - name: hashicorp/terraform
    entrypoint: sh
    args:
      - "-c"
      - |
        terraform init \
          -backend-config="bucket=regal-stone-481911-terraform-state" \
          -backend-config="prefix=terraform/state"

  # 4️⃣ Terraform Plan
  - name: hashicorp/terraform
    dir: "terraform"
    args: ["plan", "-out=tfplan"]

  # 5️⃣ Terraform Apply
  - name: hashicorp/terraform
    dir: "terraform"
    args: ["apply", "-auto-approve", "tfplan"]

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/app:latest

options:
  logging: CLOUD_LOGGING_ONLY